---
# tasks file for roles/mysql-server

#- name: copy mysql repo rpm to host
#  copy:
#    src: mysql57-community-release-el7-10.noarch.rpm
#    dest: /tmp/mysql57-community-release-el7-10.noarch.rpm
#    force: no

- name: retrieve repo rpm file for mysql community
  get_url:
    url: "{{ mysql_repo_website }}{{ mysql_community_release }}"
    dest: "/tmp/{{ mysql_community_release }}"
    mode: 0644
    force: no
    
- name: install mysql repo rpm
  yum:
    name: "/tmp/{{ mysql_community_release }}"
    state: present

- name: install mysql client/dev rpms
  yum:
      name: "{{ required_packages }}"
      state: present

- name: install pip mysqldb
  pip:
    name: MySQL-python

- name: install mysql server rpm
  yum:
    name: mysql-community-server
    state: present
  register: mysqlrpminstall

- name: stop mysqld
  service:
    name: mysqld
    state: stopped

- name: clear out mysql data dir
  file:
    path: /var/lib/mysql
    state: absent

- name: initialize mysql without a root password
  command: mysqld --initialize-insecure --user=mysql
  ignore_errors: true
  register: mysqlinit

- name: install /etc/my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf

- name: start mysqld
  service:
    name: mysqld
    state: started
    enabled: true

- block:

  - name: retrieve keys locally
    set_fact:
      vault_keys: "{{ lookup('file','~/.hashicorp_vault_keys.json') | from_json }}"
    delegate_to: localhost
    become: no

  - name: create a random password string
    set_fact:
        rand_pw_string: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits,_!$') }}"

  - name: write mysql secret to vault
    uri:
      url: "https://vault.ansiblefest.com:8201/v1/secret/AnsibleFest/database"
      method: POST
      headers:
        X-Vault-Token: "{{ vault_keys.root_token }}"
      body:
        mysqlrootpw: "{{ rand_pw_string }}"
      body_format: json
      status_code: 204
    delegate_to: localhost
    become: no

  - name: set initial root password
    mysql_user:
      name: root
      password: "{{ rand_pw_string }}"
      host: localhost
      state: present
    delegate_to: database

  when: mysqlinit is success
