---
# tasks file for roles/httpd

- name: install webserver rpms
  yum:
    name: "{{ webserver_packages }}"
    state: present

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
